### ISSUE TITLE
Internal compiler error with Graph3d

### ISSUE THREAD

**Issue by BareGamer** [pascalabcnet/pascalabcnet#3086] opened 2024-04-13 16:18 UTC
Minimum reproducible code (3.9.0.3423):
```
uses graph3d;

begin
  graph3d.Rectangle3D(0,0,0,2,2,new graph3d.Materials.ImageMaterial('your path here',1,1));
end.
```
(I know you can't create a material that way, but that's not the point)

P.S.: just tested on 3454, it also crashes the IDE now.

**Comment by SunSerega** [comment] 2024-04-13 19:55
The compiler error:
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(statement_list _statement_list)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_program_code(statement_list program_code)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(block _block)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(program_module _program_module)
   at PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter.CompileInterface(compilation_unit SyntaxUnit, unit_node_list UsedUnits, List`1 ErrorsList, List`1 WarningsList, SyntaxError parser_error, Hashtable bad_nodes, using_namespace_list namespaces, Dictionary`2 docs, Boolean debug, Boolean debugging, Boolean for_intellisense, List`1 CompiledVariables)
   at PascalABCCompiler.Compiler.CompileCurrentUnitInterface(String UnitFileName, CompilationUnit currentUnit, Dictionary`2 docs)
   at PascalABCCompiler.Compiler.CompileUnit(unit_node_list unitsFromUsesSection, Dictionary`2 directUnitsFromUsesSection, unit_or_namespace currentUnitNode, String previousPath)
   at PascalABCCompiler.Compiler.Compile()'
```
(you can click RMB>>Copy on the error in the error list window below the code)

**Comment by SunSerega** [comment] 2024-04-13 22:04
Tho on 3455 (made my own build on the latest commit of the master branch) I can only reproduce the compiler crash. When exactly does the IDE crash for you?

**Comment by SunSerega** [comment] 2024-04-13 22:53
Here is the true minimal code:
```
## uses Graph3D;
new Graph3D.Materials.ImageMaterial;
```
Well, this should crash the compiler, but @BareGamer, can you elaborate on how you got here?
`Graph3D.Materials` is a class that has an `Image` method, but has nothing called `ImageMaterial`.
There is also a global `Graph3D.ImageMaterial` subprogram, declared outside of the `Materials` class.
Neither of these can be constructed using the `new` keyword since they are subprograms and not datatypes.

**Comment by BareGamer** [comment] 2024-04-14 12:04
> Well, this should crash the compiler, but @BareGamer, can you elaborate on how you got here?

Just misremembered how to create imagematerials.

>When exactly does the IDE crash for you?

So I launched the code and it gave me an error. But then I pressed run again, and the IDE just froze.

@SunSerega

**Comment by SunSerega** [comment] 2024-04-14 14:21
> Well, this should crash the compiler

(I meant shouldn't, of course. no compiler crash is a valid behavior)

> But then I pressed run again, and the IDE just froze.

Ah, I see. That's not a crash, you just didn't close the compiler crash window, so it couldn't create a new compiler crash window and just froze waiting. I just tried and closing the compiler crash window unfreezes the IDE. But you need to minimize the main IDE window to get to the compiler crash window because it's not shown on a taskbar.
Well, that's all junky as hell, but not as much of a priority as the compiler crash you found here. And the IDE is mostly legacy code at this point, so no one wants to touch it too much...

**Comment by miks1965** [comment] 2024-04-23 08:20
Shorter code
```
uses graph3d;

begin
  new graph3d.Materials.A;
end.
```

**Comment by miks1965** [comment] 2024-04-23 16:09
![изображение](https://github.com/pascalabcnet/pascalabcnet/assets/10325391/893fa28c-b04c-465a-8faf-930293a1e1e6)
Graph3d - это common_unit_node, но в этом коде это либо namespace_node либо тип, из-за чего и падает.

**Closed** 2024-04-23 17:51 UTC
