### ISSUE TITLE
PascalABC.NET fails to read `Eto.dll`

### ISSUE THREAD

**Issue by ghost** [pascalabcnet/pascalabcnet#2928] opened 2023-10-17 14:13 UTC
I used the version for .NET Standard 2.0 that is expected to work with .NET Framework. But I always see this:

`MyForm.pas(0) : Error by reading assembly 'C:\PABCWork.NET\MyForm\Eto.dll'`

https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0

**Comment by iahunq2** [comment] 2023-10-17 14:21
> Maybe dependencies weren't found?

I use NuGet so I think this shouldn't be the case!

> Please create a .zip file with everything needed to compile and get this error.

I didn't added anycode. It's a blank PascalABC.NET WinForms project but with the Eto libraries added.

**Comment by SunSerega** [comment] 2023-10-17 14:43
> I didn't added anycode

It doesn't matter. There are always plenty of possibilities for what you could've done differently. For instance - there is no Nuget package named "Eto", so I have to make an assumption, about which package you actually meant (ig "Eto.Forms")

Well, anyway, the problem is, in fact, missing dependency. I opened the `Eto.dll` in dotPeek - saw `System.ComponentModel.Annotations.dll` in references, and tried adding it explicitly:
```
{$reference System.ComponentModel.Annotations.dll}
```
Now it all works.

---

Still, it is weird how the compiler cannot load this assembly without extra help. Maybe #2912 is related, maybe not.
So don't close this issue just yet, there is still something to figure out here.

**Comment by ibond84** [comment] 2023-11-12 13:12
fixed

**Closed by ibond84** 2023-11-12 13:12 UTC
