### ISSUE TITLE
Incorrect handling of pointers in pABC.net

### ISSUE THREAD

**Issue by Sturwandan** [pascalabcnet/pascalabcnet#2489] opened 2021-07-06 03:07 UTC
I have this code, working in Free Pascal perfectly:

```
Var
	whole: uInt64;
	fract: ^double;

Begin
	if (ParamCount <> 1) then begin
		WriteLn(stderr, 'Usage: ', ParamStr(0), ' whole_number');
		Exit;
	end;
	fract := pdouble(@whole);
	ReadStr(ParamStr(1), whole);
	WriteLn('integer : ', whole);
	WriteLn('real 64b: ', fract^:20:20);
End.
```

The code has to manipulate a 8 byte (64 bit) long memory location, which receives the first command line argument, transformed from string to an unsigned 64 bit integer, then the same memory location is interpreted as 64 bit long real number (type double) and printed out onto the standard output in 20.20 format.

While FPC handles this code perfectly, ABC has multiple issues with it:

1. stderr is not recognized. I have tried to search the documentation of pABC and still didn't find how to write the line to error output. It's incorrect for a program to mix error/debug messages and useful output. I have tried to replace it with ErrOutput as in Delphi and still got no luck.
2. Casting pointer from one type to another does not work. However, if I create another variable of type Pointer, and then assign address to it, and then to ^double variable, it works.

**Comment by SunSerega** [comment] 2021-07-06 10:26
These are 2 issues merged into 1... Otherwise:

1. Variables like `input` and `output` exist for parity with other pascal compilers. In this pascal they (as well as `Write` and `Print` methods) all use .Net functionality, in this case `Console` class. So if they don't provide something - you can implement it yourself:
   ```
   Console.Error.WriteLine($'Usage: {ParamStr(0)} whole_number');
   ```
   Note, the `{value}` syntax inside `$''` is far more readable than the `', value, '`.
   Though I agree there should also be `stderr` variable, at least for easier transition to better syntax.
2. I always double casted, aka `PDouble(pointer(@whole))`. But yeah, I don't think removing this extra cast would make it worse in any way - it looks more like something overlooked.

**Comment by Sturwandan** [comment] 2021-07-06 11:35
Thanks for your response.

1. So, I think pABC has to implement all six: stdin, Input, stdout, Output, stderr, ErrOutput.
2. Then, is there a solution to make this conditionally compiled, so the same *.pas files work the same way in FPC and pABC without modifications?
3. Well, but it's not compatible with other pascal compilers, so it is only acceptable within a conditional compilation directive, if pABC supports them. Regarding readability, I think it's about the same, but the traditional syntax is easier to understand.

Anyway, I have found a lot of other compatibility issues while trying to import FPC code into pABC. Should I create a separate bug report for each incompatibility problem I found?

4. For example, pointer arithmetic doesn't work as it was. Do I need to cast pointers to uInt64, perform arithmetic and then cast back to pointers? Such as: 
```
var a,b: ^integer, c: array[0..10] of integer;
{populate c with values}
a:=@(c[0]);
b:=Pinteger(Pointer(uInt64(Pointer(a))+8));
writeln('a^=', a^, '; (a+8)^=', b^);
```
I think this code is going to be very hard to read, compared to concise FPC syntax.

5. Also in the above example, ReadStr didn't work to grab command line parameters.

**Comment by SunSerega** [comment] 2021-07-06 12:47
Parity features can't account for every situation, and their purpose is definitely not to write code in one language and then compile using a whole different compiler. So, for instance, IMO from `stderr` and `ErrOutput` having one is enough to make old code somehow work, before refactoring it to use modern features.

For basic types, like pointer-sized integer - always look at the .Net, because one of its reasons to exist is defining common types like `string`, to use in (and between) all .Net languages, including C# and this pascal.
Separate docs for the .Net: https://docs.microsoft.com/en-us/dotnet/api/system?view=netframework-4.8

Pointer arithmetic is https://github.com/pascalabcnet/pascalabcnet/discussions/2404.

`$ifdef` certainly works, and at that - pretty much like in Delphi:
```
{$ifdef PASCALABC}
Writeln('Compiled in PascalABC or PascalABC.Net');
{$endif PASCALABC} // not necessary, {$endif} also works
```
But again, it would be easier to write 2 different sets of files, because while syntax of basic features of old pascal languages works, using it is bad in PascalABC.Net.
In particular, the fact that you placed all variable definitions in a single pile at the start of the program both makes bugs easier to miss and severely limits program performance when compiled for .Net, it's not designed for that. Variables should be defined when first used:
```
## var c: array[0..10] of integer;
// populate c with values

var a := @c[0]; // this is still bad though, and can't be fixed easily
var b := PInteger(pointer(new System.IntPtr(a) + 2*sizeof(integer)));
$'a^ = {a^}; (a+8)^ = {b^}'.Println;
```

And for a good example of where parity can't do anything: While pointer cast is a simple case - using something as unmanaged as pointers in managed .Net code is generally a complex topic that should be researched before applying. Otherwise, you'll continue doing crimes against humanity like `@c[0]` in your code.

**Comment by miks1965** [comment] 2021-07-06 13:59
PascalABC.NET is not Free Pascal

1. To cast between pointer types we must use the 'pointer' type and do two casts: to 'pointer' and then to the second pointer type
2.  Pointer arithmetics doesn't work in PascalABC.NET - it is the extension of "standard" Pascal. And we have some problems with it in .NET infrastructure. Use references instead of pointers! PascalABC.NET is not for low-level memory manipulation!

**Comment by Sturwandan** [comment] 2021-07-06 14:50
> So, for instance, IMO from stderr and ErrOutput having one is enough to make old code somehow work, before refactoring it to use modern features.

Well, when a programmer is writing code in a certain programming language, in this case, Pascal, the correct approach is to strive to use the least common denominator of all existing implementations which are still in active use. For Pascal, at the moment it would be FPC and pABC, though compatibility with Delphi would be also nice, but only if it can be achieved without sacrifices. I think, that any use of features, which works in pABC, but doesn't work in FPC must be wrapped in {$ifdef PASCALABC}.

> In particular, the fact that you placed all variable definitions in a single pile at the start of the program both makes bugs easier to miss 

If you recommend to use least possible amount of global variables, then it's a good advice. But this is usually done by placing Var between the definition of a function or a procedure and its implementation. Or in case of the nameless main procedure, the Var block has to be placed between the last procedure/function body and Begin keyword to make the variables local to the main procedure.
If your concern is, that between var declaration and its use there is a lot of code, then it only means that code has to be refactored and split into multiple functions or procedures. If you got an urge to put variable definition in the middle of a procedure, then most likely, it would be a good idea to move the piece of code, where you want to use new variables into a separate procedure, and declare the necessary variables as locals, just outside of Begin/End block.

> severely limits program performance when compiled for .Net

There should be no difference in performance between:
```
Var ...
Begin
End
```
and
```
Begin
var ...
End
```
Since the variables are declared as local to that particular Begin / End block in both samples.

@miks1965 
> To cast between pointer types we must use the 'pointer' type and do two casts: to 'pointer' and then to the second pointer type

Well, that's a problem which my bug report is about. The purpose of a cast is to tell the compiler that we are actually doing what we are doing and didn't assign incompatible values by mistake. So, one cast should be enough.

>  Use System.Console.Error instead of stderr

That's a bad option because it breaks compatibility with FPC

> ReadStr is one of the thousands functions from standard Delphi library that is absent in PascalABC.NET. I don't know this function.

This is not a function actually. it is an operator, like ReadLn, but reading the variables from a string instead of an input stream.

>  We use ParamStr(1), ParamStr(2) etc

Please read my code carefully. ParamStr(N) returns a string. I am trying to convert it into an integer.

**Comment by miks1965** [comment] 2021-07-06 17:03
The backward compatibility with old Pascals is not the main aim of our project at all. 

If you want to program in a Delphi-manner - use Free Pascal - in this case PascalABC.NET shouldn't be your choice.

To convert string into integer use ParamStr(N).ToInteger for instance or integer.TryParse(ParamStr(N), i) for safety.

In PascalABC.NET code with global variables works slower than with in-block variables.

> That's a bad option because it breaks compatibility with FPC

It's a bad option for those who programs in FPC.

I think it will be beetter to consider PascalABC.NET a new programming language that supports some features of old Pascal.

Even in modern Delphi ve have such constructs as
```
var p := 1;
for var i:=1 to 10 do
```
(since Delphi 2019)

**Comment by Sturwandan** [comment] 2021-07-06 21:26
> The backward compatibility with old Pascals is not the main aim of our project.
I agree, that staying compatible with MS-DOS is not really necessary.
However, compatibility with modern pascal, such as FPC is crucial for the project.

> To convert string into integer use ParamStr(N).ToInteger for instance or integer.TryParse(ParamStr(N), i) for safety.
That's incompatible with FPC. Why not to support ReadStr, if you already support Read and ReadLn?

> In PascalABC.NET the code with global variables works slower than with in-block variables.
Of course, the variables has to be made local, but the correct way to define local variables is to put var-block directly before Begin. It's just a syntax difference, whenever it's put inside or outside of Begin-End block, however, putting it outside (still meaning local variables) is better, because it's work everywhere, unlike putting var inside begin-end.

**Comment by miks1965** [comment] 2021-07-07 06:38
> Of course, the variables has to be made local, but the correct way to define local variables is to put var-block directly before Begin. It's just a syntax difference, whenever it's put inside or outside of Begin-End block, however, putting it outside (still meaning local variables) is better, because it's work everywhere, unlike putting var inside begin-end.

This is a statement with which we fundamentally disagree. That's a bad style nwadays

Even Delphi admits this fact: https://blog.marcocantu.com/blog/2018-october-inline-variables-delphi.html

> However, compatibility with modern pascal, such as FPC is crucial for the project.
:)

> Why not to support ReadStr, if you already support Read and ReadLn?
I think ReadStr is from some modern Delphi libraries. I don't know this function. I couldn't find this information even in Google 

But. If you are ready to create unit with such functions, we'll add this unit in our standard installation

**Comment by Sturwandan** [comment] 2021-07-07 08:19
> If you are ready to create unit with such functions, we'll add this unit in our standard installation

But ReadStr is not really a function. It's a language operator. It can't be recreated, because it has to support unlimited number of arguments of arbitrary types, same as ReadLn(); except taking values from an existing string instead of stdin.

**Comment by SunSerega** [comment] 2021-07-07 11:42
Basically this, but differently?
```
## var s := '123.456 abc 789';

var i := 1;
ReadRealFromString(s, i).Println;
ReadWordFromString(s, i).Println;
ReadIntegerFromString(s, i).Println;
```

**Comment by miks1965** [comment] 2021-07-07 13:55
> 
> 
> > If you are ready to create unit with such functions, we'll add this unit in our standard installation
> 
> But ReadStr is not really a function. It's a language operator. It can't be recreated in Pascal, because it has to support unlimited number of arguments of arbitrary types, same as ReadLn(); except taking values from an existing string instead of stdin.

Oo, ReadStr is "magic function"! It's a very very bad idea. Magic finctions are very bad for language architecture? they also significantly complicate the compiler. We definitely won't do this! 

I don't understand the term "language operator". I think it is non-standard term and it is not a part of any standard.

**Comment by Sturwandan** [comment] 2021-07-07 14:20
It's not going to work like that:
```
var r: real; s, src: string; i: integer;
begin
	src:='123.456 abc 789';
	ReadStr(src, r, s, i);
	writeln('r: ',r:4:4,', s:',s,', i:',i);
end.
{Output:}
r: 123.4560, s: abc 789, i:0
```
As you can see, str grabs the whole remainder of the string, so i gets nothing. I'm not sure how to make it limit the grab by a whitespace, but it should be same as in ReadLn;

**Comment by SunSerega** [comment] 2021-07-07 18:12
> unfortunately Pascal doesn't support variardic functions

And what's `params` then? Well, it wouldn't work in case of `Read`, because there it would need to create an array of references.
But also reading one value at a time, and returning through `Result` instead of `var`-parameters is usually better. Old `Read`-subprograms are obsolete.

**Comment by miks1965** [comment] 2021-07-07 18:24
> Perhaps, pABCn should remove this limitation and move aforementioned magic functions into a unit, implemented on the pascal itself?

It's a bad idea. The code that supports magic functions such as Read consosts of >500 lines. We wrote it only fo reason of compatibility with old Pascal. But this code significantly increases the fragility of the compiler and a number of future errors in compiler infrastructure

**Comment by Sturwandan** [comment] 2021-07-08 01:13
> It's a bad idea.

How is it a bad idea? I suggest to remove magic functions from the compiler, making it only provide primitives like _read and _write which simply read requested number of characters from the stdin and write to stdout. Then implement a really useful extension to Pascal language: passing arbitrary number of arguments into a procedure or function and using this new feature, implement all writing and reading functions within the standard unit (which doesn't require uses directive, but works same way as if it was on place).

> But this code significantly increases the fragility of the compiler and a number of future errors in compiler infrastructure

That's why my suggestion. Remove them all from the compiler, move them to a unit written in pascal itself. Same way as it is done in C, where printf(); scanf(); and other things are not part of C compiler infrastructure, but rather they reside in libc, which is just a library like any other library and you don't have to link with it, if you are ready to implement everything yourself.

Same can be done in Pascal. Implicit loading default library could be disabled with a compiler switch if a user strives for smaller executable.

**Closed** 2021-07-08 06:07 UTC

**Comment by Sturwandan** [comment] 2021-07-08 06:11
Why is the bug closed? Did you fix the actual problem?

Do I need to open separate bug reports for other problems, discussed in this thread?

**Comment by miks1965** [comment] 2021-07-08 06:16
> Remove them all from the compiler, move them to a unit written in pascal itself. 
ReadStr is not a standard feature of Pascal standard. This is an artefact of a FPC dialect. 
We have an another dialect of Pascal Language :)

**Comment by Sturwandan** [comment] 2021-07-08 06:26
@miks1965 
https://wiki.freepascal.org/Extended_Pascal#Already_supported_features
That's a feature of Pascal language's updated official standard, actually.

What about other things? Namely, support for stderr ouput?

**Comment by miks1965** [comment] 2021-07-08 06:48
Can you give some page with specification of ReadStr?

Is the stderr output a part of a standard?

As for pointers... In nowadays Delphi help:
http://docwiki.embarcadero.com/RADStudio/Sydney/en/Pointers_and_Pointer_Types_(Delphi)
You can read here: "Finally, pointers are sometimes the only way to circumvent Delphi's strict data typing. By referencing a variable with an all-purpose Pointer, casting the Pointer to a more specific type, and then dereferencing it, you can treat the data stored by any variable as if it belonged to any type. For example, the following code assigns data stored in a real variable to an integer variable: " 
```
type
  PInteger = ^Integer;
var
  R: Single;
  I: Integer;
  P: Pointer;
  PI: PInteger;
begin
  ...
  P := @R;
  PI := PInteger(P);
  I := PI^;
end;
```
I don't see your feature even in modern Delphi

**Comment by miks1965** [comment] 2021-07-08 08:23
It's not a bug. It's a difference between our dialect and FPC dialect.

I think - a better way to open discussion on these questions here
https://github.com/pascalabcnet/pascalabcnet/discussions

**Comment by Sturwandan** [comment] 2021-07-08 10:43
1. https://www.freepascal.org/docs-html/rtl/system/readstr.html Here, or http://pascal-central.com/docs/iso10206.pdf here, page 86.
In short, it's supposed to produce exactly same result as Read, except it's applied to a string instead of a file.

2. Well, I don't really care about Delphi. But if the code contains an explicit typecast, then it's an indication, that the programmer knows what it is doing. All pointers, including Pointer, Pinteger, Preal have same size on the same machine and they are stored in the exactly same way on the underlying level, so typecast from one to other should be always permitted.
However, assignment of pointers to variables of different pointer types without typecasts is dodgy, so it should generate an error or a warning.

At the moment, PascalABC net is doing the reverse. 

3. Is the stderr output a part of a standard? 
I do not know, however, every single console program both in Unix and Windows always has three file descriptors opened: stdin, stdout and stderr. In Delphi they are called Input, Output and ErrOutput, however, as far as I know.

**Comment by miks1965** [comment] 2021-07-08 13:05
I think that the main problem is in the fact that you consider PascalABC.NET as a language that you want but not a language which it really is. But the truth is that our goal has never been and will never be the implementation of extended pascal standard. We have implemented to this moment approx 95% of features of standard pascal and some features of extended (more exactly - extended pascal was not elseware our goal - we compared our compiler with Delphi, some ideas are from C#, F#, C++, Python and other ideas are from our educational purposes. Today the general line of PascalABC.NET development is far away from Extended Pascal. 

It is unlikely that we will develop features of Extended Pascal because for us it is "the history"

Also I'll point out that even FPC doesn't implevent even a half of features of extended Pascal ))

As for stderr - the PascalABC.NET is at first .NET language and uses all .NET libraries with their own standards. For example? Console.Out and Console.Error

**Comment by Sturwandan** [comment] 2021-07-08 15:20
> But the truth is that our goal has never been and will never be the implementation of extended pascal standard.

I did not suggest to implement extended standard as the whole thing. Just ReadStr and WriteStr for now. 

>  We have implemented to this moment approx 95% of features of standard pascal

Is it documented, what is present and what is missing exactly?

> As for stderr - the PascalABC.NET is at first .NET language and uses all .NET libraries with their own standards. For example? Console.Out and Console.Error

My intent is to have programs work the exactly same way in both FPC and ABC, as long as they only use certain well-defined features, which should be enough to cover all the basic programming needs. 

What does a typical console program need? It needs to work with all three three standard channels and command line arguments at the very least. Command line arguments are strings, so the language has to provide some means to extract information out of them. 

And those features has to be available via some means, common between different implementations. I cannot use aforementioned Console.Error stuff directly, because it won't work elsewhere. But if you have wrapped it into WriteLn(stderr, ...), then I don't care what lies underneath, as long as it's easy enough to write code which works in all existing implementations.

**Comment by miks1965** [comment] 2021-07-08 18:44
In Delphi - ErrOutput
http://docwiki.embarcadero.com/Libraries/Sydney/en/System.ErrOutput

**Comment by Sturwandan** [comment] 2021-07-09 08:31
Yeah. Free Pascal supports both ErrOutput and stderr, which I think is good, for it's easier to remember the latter, then former

**Comment by miks1965** [comment] 2021-07-09 11:32
How to redirect ErrOutput to file?
This code fails in FPC:
```
  Assign(ErrOutput,'w.txt');
  Write(ErrOutput,44);
```

**Comment by Sturwandan** [comment] 2021-07-09 15:50
Isn't ErrOutput a constant?

Anyway, the easiest option is to write something like that in shell:

```
your_program.exe 2> errors.log
```

However, if you want to add a feature to your program to have errors written into stderr or a file, you can have a global text file variable, which you make equal ErrOutput by default, then if command line parse encountered something like --errors=file.name then you are going to open file.name for appending and put its file descriptor into the variable.

**Comment by miks1965** [comment] 2021-07-09 19:14
Oo, strange that uou are not familiar with FPC ...

And what's about your first code example? 
```
WriteLn(stderr, 'Usage: ', ParamStr(0), ' whole_number');
```
If we use FPC, where we should see the output result?

**Comment by Sturwandan** [comment] 2021-07-10 02:17
@miks1965 sorry, but I don't quite understand what are you trying to do.

stdin, stdout and stderr are three file descriptors, which are automatically opened when any program starts. On the underlying level they are integers with values 0, 1 and 2 respectively.

Normally, when the program is started from the terminal, all three descriptors are pointing to the aforementioned terminal for input and output.

However, any of them could be redirected with shell redirection operators. Most of them are common between Unix shells and cmd, because cmd was modeled after DOS's command.com and DOS was partially modeled after Unix systems.
```
> file.txt — redirects stdout to file.txt, if file existed, its former content is lost.
>> log.txt — redirects stdout to log.txt, but it will be appended to the end of file.
2> err.txt — redirects stderr to file err.txt
2>&1 — redirects stderr to stdout
1>&2 — redirects stdout to stderr (it's almost never useful)
| foo — redirects stdout to stdin of foo command
|& bar — redirects both stdout and stderr to bar stdin
2>&1 | — same as above, but works in cmd too.
< input.txt — redirects stdin to input.txt
```

Those are the most basic redirections, some command shells support more operators. With them, a program can be designed in a simpler way. For example, if you want to input data from input.txt and output it to output.txt, but also support input and output from the terminal (keyboard+screen), then you can simply use ReadLn and WriteLn and don't care about files. Because if necessary your program can be launched by the user with ``cool_program < input.txt > output.txt``. Though bigger and more serious programs usually support options to read input and output file names from the command line arguments, which requires a bit more code.

**Comment by Sturwandan** [comment] 2021-07-13 14:13
@miks1965 I see that you have added ErrOutput option, that's nice, but how about pointer cast syntax? Are you going to make it so that pointers can be cast from all pointer types to to all pointer types and integer types which are same or wider than them without an error? If the pointers are just addresses, it doesn't make sense to require double cast every time.
