### ISSUE TITLE
Type inference not working properly

### ISSUE THREAD

**Issue by sglienke** [pascalabcnet/pascalabcnet#723] opened 2018-03-15 16:13 UTC
I have following code:

```
{$reference 'System.Reactive.dll'}

uses
  System,
  System.Reactive.Linq;
  
begin
  var interval := Observable.Interval(TimeSpan.FromMilliseconds(500));
  var groups := interval.GroupBy(x -> x mod 10);
  Readln;
end.
```

The result of Observable.Interval is clearly IObservable<Int64> as you can see:

![image](https://user-images.githubusercontent.com/6238697/37475751-b59f10e2-2873-11e8-9f27-538a113f59d4.png)

However it seems some information is lost when assigning that to the interval variable and infering its type:

![image](https://user-images.githubusercontent.com/6238697/37476011-53699946-2874-11e8-9cd9-419fa48d513d.png)

And thus any further code completion seems to not work (like getting any members of `group`).

It furthermore seems to fail once lambdas get a bit more complex:

This compiles:

```
  groups.Subscribe(g -> 
    begin 
      Writeln('Group started with key: ', g.Key); 
//      g.Subscribe(x-> Writeln(x)); 
    end);
```

But as soon as I remove the comment from the second line it gives this error:

Reactive.pas(10) : It is impossible to infer result type of lambda expression

When I help the compiler a bit it compiles:

```
  groups.Subscribe(procedure(g: IGroupedObservable<Int64,Int64>) -> 
    begin 
      Writeln('Group started with key: ', g.Key); 
      g.Subscribe(x-> Writeln(x)); 
    end);
```

**Comment by miks1965** [comment] 2018-05-10 15:07
We close this issue.

This issue contains two small bugs. 

The first is an intellisense bug in some complex situation. Our intellisense is not so powerful in many situations.

The second is not a bug: our type inferense algorithm doesn't work in this situation. The algorithm on syntactic level considers x-> Writeln(x) as a lambda function - not a lambda procedure.

**Closed by miks1965** 2018-05-10 15:07 UTC
Labels: bug
